version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/merge-frontend
    overwrite: yes
permissions:
  - object: /home/ubuntu/merge-frontend
    pattern: "**"
    owner: root
    group: root
    mode: 755
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
